### ISSUE TITLE
[BUG] Filters are not respected in csv exports

### ISSUE THREAD

**Issue by DogukanL** [opensearch-project/reporting#405]
Filters are not respected in csv exports.

1. Go to Discover tab
2. Save the current search
3. Filter results
4. On the top right corner click on "Reporting" -> "Generate CSV"
5. The CSV export will not have the same documents as the discover tab you've exported it from

I would expect filters to be applied.

I am using the official docker images from opensearchproject. I've tried it both on version 1.3.2 and version 2.1.0.

**Comment by joshuali925** [comment]
Hi, I'm not able to reproduce this issue. It's likely because after filtering results (step 3), the search needs to be saved again so filters will be saved. If you are still having issue after doing that, could you provide some details about:

1. does this issue happen to all saved searches?
2. if not, does this happen to a specific filter, or a specific index pattern?
3. if so, could you provide the filter or index pattern mapping / sample docs that is causing this issue?

If it worked after saving filters to saved search, then you can ignore the above. Thanks

**Comment by DogukanL** [comment]
Hey @joshuali925,

It works after saving the search again but one would expect filters to be applied regardless. It is a bit unintuitive.
